// <auto-generated />
using System;
using FamilyAccountApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyAccountApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320062413_AddBudgetBankAccountAndAccountingEntryCurrency")]
    partial class AddBudgetBankAccountAndAccountingEntryCurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Account", b =>
                {
                    b.Property<int>("IdAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAccount")
                        .HasComment("Identificador único autoincremental de la cuenta contable.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccount"));

                    b.Property<bool>("AllowsMovements")
                        .HasColumnType("bit")
                        .HasColumnName("allowsMovements")
                        .HasComment("Indica si la cuenta acepta asientos contables directos (true) o es solo agrupadora (false).");

                    b.Property<string>("CodeAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codeAccount")
                        .HasComment("Código jerárquico único de la cuenta. Ej: '1', '1.1', '1.1.01'.");

                    b.Property<int?>("IdAccountParent")
                        .HasColumnType("int")
                        .HasColumnName("idAccountParent")
                        .HasComment("FK a la cuenta padre. NULL indica que es una cuenta raíz.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive")
                        .HasComment("Indica si la cuenta está activa y disponible para su uso.");

                    b.Property<int>("LevelAccount")
                        .HasColumnType("int")
                        .HasColumnName("levelAccount")
                        .HasComment("Nivel jerárquico dentro del plan de cuentas. 1 = cuenta raíz.");

                    b.Property<string>("NameAccount")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nameAccount")
                        .HasComment("Nombre descriptivo de la cuenta contable.");

                    b.Property<string>("TypeAccount")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("typeAccount")
                        .HasComment("Tipo contable: Activo | Pasivo | Capital | Ingreso | Gasto | Control.");

                    b.HasKey("IdAccount");

                    b.HasIndex("CodeAccount")
                        .IsUnique()
                        .HasDatabaseName("UQ_account_codeAccount");

                    b.HasIndex("IdAccountParent");

                    b.ToTable("account", t =>
                        {
                            t.HasComment("Catálogo de cuentas contables con jerarquía auto-referenciada. Permite registrar el plan de cuentas con padres e hijos. typeAccount: Activo, Pasivo, Capital, Ingreso, Gasto, Control.");

                            t.HasCheckConstraint("CK_account_typeAccount", "typeAccount IN ('Activo', 'Pasivo', 'Capital', 'Ingreso', 'Gasto', 'Control')");
                        });

                    b.HasData(
                        new
                        {
                            IdAccount = 1,
                            AllowsMovements = false,
                            CodeAccount = "1",
                            IsActive = true,
                            LevelAccount = 1,
                            NameAccount = "Activo",
                            TypeAccount = "Activo"
                        },
                        new
                        {
                            IdAccount = 2,
                            AllowsMovements = false,
                            CodeAccount = "2",
                            IsActive = true,
                            LevelAccount = 1,
                            NameAccount = "Pasivo",
                            TypeAccount = "Pasivo"
                        },
                        new
                        {
                            IdAccount = 3,
                            AllowsMovements = false,
                            CodeAccount = "3",
                            IsActive = true,
                            LevelAccount = 1,
                            NameAccount = "Capital",
                            TypeAccount = "Capital"
                        },
                        new
                        {
                            IdAccount = 4,
                            AllowsMovements = false,
                            CodeAccount = "4",
                            IsActive = true,
                            LevelAccount = 1,
                            NameAccount = "Ingreso",
                            TypeAccount = "Ingreso"
                        },
                        new
                        {
                            IdAccount = 5,
                            AllowsMovements = false,
                            CodeAccount = "5",
                            IsActive = true,
                            LevelAccount = 1,
                            NameAccount = "Gasto",
                            TypeAccount = "Gasto"
                        },
                        new
                        {
                            IdAccount = 6,
                            AllowsMovements = false,
                            CodeAccount = "6",
                            IsActive = true,
                            LevelAccount = 1,
                            NameAccount = "Control",
                            TypeAccount = "Control"
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.AccountingEntry", b =>
                {
                    b.Property<int>("IdAccountingEntry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAccountingEntry")
                        .HasComment("Identificador único autoincremental del asiento contable.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccountingEntry"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Fecha y hora de creación del asiento contable.");

                    b.Property<DateOnly>("DateEntry")
                        .HasColumnType("date")
                        .HasColumnName("dateEntry")
                        .HasComment("Fecha contable del asiento.");

                    b.Property<string>("DescriptionEntry")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descriptionEntry")
                        .HasComment("Descripción general del asiento contable.");

                    b.Property<decimal>("ExchangeRateValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("exchangeRateValue")
                        .HasComment("Tipo de cambio utilizado al momento de registrar el asiento contable.");

                    b.Property<int>("IdCurrency")
                        .HasColumnType("int")
                        .HasColumnName("idCurrency")
                        .HasComment("FK a la moneda en la que fue registrado el asiento contable.");

                    b.Property<int>("IdFiscalPeriod")
                        .HasColumnType("int")
                        .HasColumnName("idFiscalPeriod")
                        .HasComment("FK al período fiscal al que pertenece el asiento contable.");

                    b.Property<string>("NumberEntry")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("numberEntry")
                        .HasComment("Número o consecutivo del asiento contable dentro del período fiscal.");

                    b.Property<string>("ReferenceEntry")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("referenceEntry")
                        .HasComment("Referencia opcional del asiento, como número de documento, factura o comprobante externo.");

                    b.Property<string>("StatusEntry")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("statusEntry")
                        .HasComment("Estado del asiento contable: Borrador | Publicado | Anulado.");

                    b.HasKey("IdAccountingEntry");

                    b.HasIndex("IdCurrency")
                        .HasDatabaseName("IX_accountingEntry_idCurrency");

                    b.HasIndex("IdFiscalPeriod", "NumberEntry")
                        .IsUnique()
                        .HasDatabaseName("UQ_accountingEntry_idFiscalPeriod_numberEntry");

                    b.ToTable("accountingEntry", t =>
                        {
                            t.HasComment("Cabecera del asiento contable. Agrupa las líneas de débito y crédito registradas dentro de un período fiscal determinado.");

                            t.HasCheckConstraint("CK_accountingEntry_statusEntry", "statusEntry IN ('Borrador', 'Publicado', 'Anulado')");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.AccountingEntryLine", b =>
                {
                    b.Property<int>("IdAccountingEntryLine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAccountingEntryLine")
                        .HasComment("Identificador único autoincremental de la línea del asiento contable.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccountingEntryLine"));

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("creditAmount")
                        .HasComment("Monto registrado al crédito. Debe ser mayor que cero solo cuando la línea es de crédito.");

                    b.Property<decimal>("DebitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("debitAmount")
                        .HasComment("Monto registrado al débito. Debe ser mayor que cero solo cuando la línea es de débito.");

                    b.Property<string>("DescriptionLine")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descriptionLine")
                        .HasComment("Descripción opcional y específica de la línea del asiento contable.");

                    b.Property<int>("IdAccount")
                        .HasColumnType("int")
                        .HasColumnName("idAccount")
                        .HasComment("FK a la cuenta contable afectada por esta línea.");

                    b.Property<int>("IdAccountingEntry")
                        .HasColumnType("int")
                        .HasColumnName("idAccountingEntry")
                        .HasComment("FK al asiento contable al que pertenece la línea.");

                    b.Property<int?>("IdCostCenter")
                        .HasColumnType("int")
                        .HasColumnName("idCostCenter")
                        .HasComment("FK opcional al centro de costo asociado a esta línea del asiento contable.");

                    b.HasKey("IdAccountingEntryLine");

                    b.HasIndex("IdAccount")
                        .HasDatabaseName("IX_accountingEntryLine_idAccount");

                    b.HasIndex("IdAccountingEntry")
                        .HasDatabaseName("IX_accountingEntryLine_idAccountingEntry");

                    b.HasIndex("IdCostCenter")
                        .HasDatabaseName("IX_accountingEntryLine_idCostCenter")
                        .HasFilter("[idCostCenter] IS NOT NULL");

                    b.ToTable("accountingEntryLine", t =>
                        {
                            t.HasComment("Líneas del asiento contable. Cada línea afecta una cuenta contable con un monto al débito o al crédito.");

                            t.HasCheckConstraint("CK_accountingEntryLine_singleSidedAmount", "((debitAmount > 0 AND creditAmount = 0) OR (debitAmount = 0 AND creditAmount > 0))");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.BankAccount", b =>
                {
                    b.Property<int>("IdBankAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idBankAccount")
                        .HasComment("Identificador único autoincremental de la cuenta bancaria.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBankAccount"));

                    b.Property<string>("AccountHolder")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("accountHolder")
                        .HasComment("Titular de la cuenta bancaria.");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("accountNumber")
                        .HasComment("Número de cuenta bancaria o IBAN.");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("bankName")
                        .HasComment("Nombre de la entidad bancaria.");

                    b.Property<string>("CodeBankAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codeBankAccount")
                        .HasComment("Código interno único de la cuenta bancaria.");

                    b.Property<int>("IdAccount")
                        .HasColumnType("int")
                        .HasColumnName("idAccount")
                        .HasComment("FK a la cuenta contable que representa esta cuenta bancaria en el mayor.");

                    b.Property<int>("IdCurrency")
                        .HasColumnType("int")
                        .HasColumnName("idCurrency")
                        .HasComment("FK a la moneda manejada por la cuenta bancaria.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive")
                        .HasComment("Indica si la cuenta bancaria está activa para operaciones y conciliaciones.");

                    b.HasKey("IdBankAccount");

                    b.HasIndex("AccountNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_bankAccount_accountNumber");

                    b.HasIndex("CodeBankAccount")
                        .IsUnique()
                        .HasDatabaseName("UQ_bankAccount_codeBankAccount");

                    b.HasIndex("IdAccount")
                        .HasDatabaseName("IX_bankAccount_idAccount");

                    b.HasIndex("IdCurrency")
                        .HasDatabaseName("IX_bankAccount_idCurrency");

                    b.ToTable("bankAccount", t =>
                        {
                            t.HasComment("Cuentas bancarias vinculadas a cuentas contables y monedas para conciliación y control de efectivo.");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Budget", b =>
                {
                    b.Property<int>("IdBudget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idBudget")
                        .HasComment("Identificador único autoincremental del presupuesto.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBudget"));

                    b.Property<decimal>("AmountBudget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amountBudget")
                        .HasComment("Monto presupuestado para la cuenta contable en el período fiscal indicado.");

                    b.Property<int>("IdAccount")
                        .HasColumnType("int")
                        .HasColumnName("idAccount")
                        .HasComment("FK a la cuenta contable asociada al presupuesto.");

                    b.Property<int>("IdFiscalPeriod")
                        .HasColumnType("int")
                        .HasColumnName("idFiscalPeriod")
                        .HasComment("FK al período fiscal al que aplica el presupuesto.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive")
                        .HasComment("Indica si el presupuesto está activo para control y consulta.");

                    b.Property<string>("NotesBudget")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("notesBudget")
                        .HasComment("Notas u observaciones opcionales del presupuesto.");

                    b.HasKey("IdBudget");

                    b.HasIndex("IdFiscalPeriod")
                        .HasDatabaseName("IX_budget_idFiscalPeriod");

                    b.HasIndex("IdAccount", "IdFiscalPeriod")
                        .IsUnique()
                        .HasDatabaseName("UQ_budget_idAccount_idFiscalPeriod");

                    b.ToTable("budget", t =>
                        {
                            t.HasComment("Presupuestos contables por cuenta y período fiscal para control y análisis financiero.");

                            t.HasCheckConstraint("CK_budget_amountBudget_positive", "amountBudget > 0");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("IdContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idContact")
                        .HasComment("Identificador único autoincremental del contacto.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContact"));

                    b.Property<string>("CodeContact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codeContact")
                        .HasComment("Código único de identificación del contacto. Usado internamente para referencias rápidas.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name")
                        .HasComment("Nombre completo o razón social del contacto.");

                    b.HasKey("IdContact");

                    b.HasIndex("CodeContact")
                        .IsUnique()
                        .HasDatabaseName("UQ_contact_codeContact");

                    b.ToTable("contact", t =>
                        {
                            t.HasComment("Catálogo de contactos del sistema: clientes, proveedores u otras entidades externas. Cada contacto puede tener uno o más tipos asignados a través de la tabla contactContactType.");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ContactContactType", b =>
                {
                    b.Property<int>("IdContactContactType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idContactContactType")
                        .HasComment("Identificador único autoincremental de la asociación contacto-tipo.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContactContactType"));

                    b.Property<int>("IdContact")
                        .HasColumnType("int")
                        .HasColumnName("idContact")
                        .HasComment("FK al contacto.");

                    b.Property<int>("IdContactType")
                        .HasColumnType("int")
                        .HasColumnName("idContactType")
                        .HasComment("FK al tipo de contacto.");

                    b.HasKey("IdContactContactType");

                    b.HasIndex("IdContactType");

                    b.HasIndex("IdContact", "IdContactType")
                        .IsUnique()
                        .HasDatabaseName("UQ_contactContactType_idContact_idContactType");

                    b.ToTable("contactContactType", t =>
                        {
                            t.HasComment("Tabla de asociación muchos-a-muchos entre contactos y tipos de contacto. Permite que un mismo contacto sea clasificado como Cliente, Proveedor u otros tipos simultáneamente. No se permite la misma combinación contacto-tipo dos veces.");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ContactType", b =>
                {
                    b.Property<int>("IdContactType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idContactType")
                        .HasComment("Identificador único autoincremental del tipo de contacto.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContactType"));

                    b.Property<string>("CodeContactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codeContactType")
                        .HasComment("Código abreviado único del tipo de contacto. Ej: 'CLI' (Cliente), 'PRO' (Proveedor).");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name")
                        .HasComment("Nombre descriptivo del tipo de contacto. Ej: 'Cliente', 'Proveedor'.");

                    b.HasKey("IdContactType");

                    b.HasIndex("CodeContactType")
                        .IsUnique()
                        .HasDatabaseName("UQ_contactType_codeContactType");

                    b.ToTable("contactType", t =>
                        {
                            t.HasComment("Catálogo de tipos de contacto. Permite clasificar un contacto con una o más categorías (ej: Cliente, Proveedor). Los valores se asignan a contactos a través de la tabla contactContactType.");
                        });

                    b.HasData(
                        new
                        {
                            IdContactType = 1,
                            CodeContactType = "CLI",
                            Name = "Cliente"
                        },
                        new
                        {
                            IdContactType = 2,
                            CodeContactType = "PRO",
                            Name = "Proveedor"
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.CostCenter", b =>
                {
                    b.Property<int>("IdCostCenter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCostCenter")
                        .HasComment("Identificador único autoincremental del centro de costo.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCostCenter"));

                    b.Property<string>("CodeCostCenter")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codeCostCenter")
                        .HasComment("Código único del centro de costo. Ejemplo: ADM, VTA, PROD.");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isActive")
                        .HasComment("Indica si el centro de costo está activo y disponible para su uso en asientos contables.");

                    b.Property<string>("NameCostCenter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nameCostCenter")
                        .HasComment("Nombre descriptivo del centro de costo. Ejemplo: Administración, Ventas.");

                    b.HasKey("IdCostCenter");

                    b.HasIndex("CodeCostCenter")
                        .IsUnique()
                        .HasDatabaseName("UQ_costCenter_codeCostCenter");

                    b.ToTable("costCenter", t =>
                        {
                            t.HasComment("Centros de costo para clasificar los asientos contables por área, proyecto o departamento.");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("IdCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCurrency")
                        .HasComment("Identificador único autoincremental de la moneda.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurrency"));

                    b.Property<string>("CodeCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("codeCurrency")
                        .HasComment("Código único de la moneda según estándar internacional. Ejemplo: CRC, USD, EUR.");

                    b.Property<string>("NameCurrency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nameCurrency")
                        .HasComment("Nombre descriptivo de la moneda. Ejemplo: Colón costarricense, Dólar estadounidense.");

                    b.Property<string>("SymbolCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("symbolCurrency")
                        .HasComment("Símbolo representativo de la moneda. Ejemplo: ₡, $, €.");

                    b.HasKey("IdCurrency");

                    b.HasIndex("CodeCurrency")
                        .IsUnique()
                        .HasDatabaseName("UQ_currency_codeCurrency");

                    b.ToTable("currency", t =>
                        {
                            t.HasComment("Monedas disponibles en el sistema contable para registrar operaciones y tipos de cambio.");
                        });

                    b.HasData(
                        new
                        {
                            IdCurrency = 1,
                            CodeCurrency = "CRC",
                            NameCurrency = "Colón costarricense",
                            SymbolCurrency = "₡"
                        },
                        new
                        {
                            IdCurrency = 2,
                            CodeCurrency = "USD",
                            NameCurrency = "Dólar estadounidense",
                            SymbolCurrency = "$"
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<int>("IdExchangeRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idExchangeRate")
                        .HasComment("Identificador único autoincremental del tipo de cambio.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExchangeRate"));

                    b.Property<int>("IdCurrency")
                        .HasColumnType("int")
                        .HasColumnName("idCurrency")
                        .HasComment("FK a la moneda a la que pertenece este tipo de cambio.");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date")
                        .HasColumnName("rateDate")
                        .HasComment("Fecha efectiva del tipo de cambio.");

                    b.Property<decimal>("RateValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("rateValue")
                        .HasComment("Valor del tipo de cambio de la moneda respecto a la moneda base definida por la organización.");

                    b.HasKey("IdExchangeRate");

                    b.HasIndex("IdCurrency")
                        .HasDatabaseName("IX_exchangeRate_idCurrency");

                    b.HasIndex("IdCurrency", "RateDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_exchangeRate_idCurrency_rateDate");

                    b.ToTable("exchangeRate", t =>
                        {
                            t.HasComment("Tipos de cambio por moneda y fecha para soportar operaciones multi-moneda en el sistema contable.");

                            t.HasCheckConstraint("CK_exchangeRate_rateValue_positive", "rateValue > 0");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.FiscalPeriod", b =>
                {
                    b.Property<int>("IdFiscalPeriod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idFiscalPeriod")
                        .HasComment("Identificador único autoincremental del período fiscal.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFiscalPeriod"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("endDate")
                        .HasComment("Fecha de fin del período fiscal (último día del mes).");

                    b.Property<int>("MonthPeriod")
                        .HasColumnType("int")
                        .HasColumnName("monthPeriod")
                        .HasComment("Número de mes del período fiscal: 1=Enero, ..., 12=Diciembre.");

                    b.Property<string>("NamePeriod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("namePeriod")
                        .HasComment("Nombre descriptivo del período (p. ej. 'Enero 2026').");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("startDate")
                        .HasComment("Fecha de inicio del período fiscal (primer día del mes).");

                    b.Property<string>("StatusPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("statusPeriod")
                        .HasComment("Estado del período: 'Abierto' permite movimientos, 'Cerrado' no admite nuevos registros, 'Bloqueado' está bloqueado administrativamente.");

                    b.Property<int>("YearPeriod")
                        .HasColumnType("int")
                        .HasColumnName("yearPeriod")
                        .HasComment("Año calendario del período fiscal (p. ej. 2026).");

                    b.HasKey("IdFiscalPeriod");

                    b.HasIndex("YearPeriod", "MonthPeriod")
                        .IsUnique()
                        .HasDatabaseName("UQ_fiscalPeriod_yearPeriod_monthPeriod");

                    b.ToTable("fiscalPeriod", t =>
                        {
                            t.HasComment("Períodos fiscales del sistema contable. Cada período representa un mes de un año y controla si se permiten movimientos contables en ese período.");

                            t.HasCheckConstraint("CK_fiscalPeriod_statusPeriod", "statusPeriod IN ('Abierto', 'Cerrado', 'Bloqueado')");
                        });

                    b.HasData(
                        new
                        {
                            IdFiscalPeriod = 1,
                            EndDate = new DateOnly(2026, 1, 31),
                            MonthPeriod = 1,
                            NamePeriod = "Enero 2026",
                            StartDate = new DateOnly(2026, 1, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        },
                        new
                        {
                            IdFiscalPeriod = 2,
                            EndDate = new DateOnly(2026, 2, 28),
                            MonthPeriod = 2,
                            NamePeriod = "Febrero 2026",
                            StartDate = new DateOnly(2026, 2, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        },
                        new
                        {
                            IdFiscalPeriod = 3,
                            EndDate = new DateOnly(2026, 3, 31),
                            MonthPeriod = 3,
                            NamePeriod = "Marzo 2026",
                            StartDate = new DateOnly(2026, 3, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        },
                        new
                        {
                            IdFiscalPeriod = 4,
                            EndDate = new DateOnly(2026, 4, 30),
                            MonthPeriod = 4,
                            NamePeriod = "Abril 2026",
                            StartDate = new DateOnly(2026, 4, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        },
                        new
                        {
                            IdFiscalPeriod = 5,
                            EndDate = new DateOnly(2026, 5, 31),
                            MonthPeriod = 5,
                            NamePeriod = "Mayo 2026",
                            StartDate = new DateOnly(2026, 5, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        },
                        new
                        {
                            IdFiscalPeriod = 6,
                            EndDate = new DateOnly(2026, 6, 30),
                            MonthPeriod = 6,
                            NamePeriod = "Junio 2026",
                            StartDate = new DateOnly(2026, 6, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        },
                        new
                        {
                            IdFiscalPeriod = 7,
                            EndDate = new DateOnly(2026, 7, 31),
                            MonthPeriod = 7,
                            NamePeriod = "Julio 2026",
                            StartDate = new DateOnly(2026, 7, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        },
                        new
                        {
                            IdFiscalPeriod = 8,
                            EndDate = new DateOnly(2026, 8, 31),
                            MonthPeriod = 8,
                            NamePeriod = "Agosto 2026",
                            StartDate = new DateOnly(2026, 8, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        },
                        new
                        {
                            IdFiscalPeriod = 9,
                            EndDate = new DateOnly(2026, 9, 30),
                            MonthPeriod = 9,
                            NamePeriod = "Septiembre 2026",
                            StartDate = new DateOnly(2026, 9, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        },
                        new
                        {
                            IdFiscalPeriod = 10,
                            EndDate = new DateOnly(2026, 10, 31),
                            MonthPeriod = 10,
                            NamePeriod = "Octubre 2026",
                            StartDate = new DateOnly(2026, 10, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        },
                        new
                        {
                            IdFiscalPeriod = 11,
                            EndDate = new DateOnly(2026, 11, 30),
                            MonthPeriod = 11,
                            NamePeriod = "Noviembre 2026",
                            StartDate = new DateOnly(2026, 11, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        },
                        new
                        {
                            IdFiscalPeriod = 12,
                            EndDate = new DateOnly(2026, 12, 31),
                            MonthPeriod = 12,
                            NamePeriod = "Diciembre 2026",
                            StartDate = new DateOnly(2026, 12, 1),
                            StatusPeriod = "Abierto",
                            YearPeriod = 2026
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProduct")
                        .HasComment("Identificador único autoincremental del producto.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("CodeProduct")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codeProduct")
                        .HasComment("Código interno único del producto. Definido por la empresa, distinto al código de barras del fabricante.");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nameProduct")
                        .HasComment("Nombre interno del producto usado en el sistema.");

                    b.HasKey("IdProduct");

                    b.HasIndex("CodeProduct")
                        .IsUnique()
                        .HasDatabaseName("UQ_product_codeProduct");

                    b.ToTable("product", t =>
                        {
                            t.HasComment("Catálogo interno de productos de la empresa. Un producto puede estar relacionado con uno o más SKUs escaneables (productProductSKU) y pertenecer a una o más categorías (productProductCategory).");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<int>("IdProductCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProductCategory")
                        .HasComment("Identificador único autoincremental de la categoría de producto.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductCategory"));

                    b.Property<string>("NameProductCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nameProductCategory")
                        .HasComment("Nombre descriptivo de la categoría. Ej: 'Lácteos', 'Limpieza', 'Bebidas'.");

                    b.HasKey("IdProductCategory");

                    b.ToTable("productCategory", t =>
                        {
                            t.HasComment("Catálogo de categorías de productos. Permite agrupar y clasificar los productos internos para facilitar su búsqueda y organización. Un producto puede pertenecer a múltiples categorías a través de productProductCategory.");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ProductProductCategory", b =>
                {
                    b.Property<int>("IdProductProductCategory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProductProductCategory")
                        .HasComment("Identificador único autoincremental de la asociación producto-categoría.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductProductCategory"));

                    b.Property<int>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("idProduct")
                        .HasComment("FK al producto interno.");

                    b.Property<int>("IdProductCategory")
                        .HasColumnType("int")
                        .HasColumnName("idProductCategory")
                        .HasComment("FK a la categoría de producto.");

                    b.HasKey("IdProductProductCategory");

                    b.HasIndex("IdProductCategory");

                    b.HasIndex("IdProduct", "IdProductCategory")
                        .IsUnique()
                        .HasDatabaseName("UQ_productProductCategory_idProduct_idProductCategory");

                    b.ToTable("productProductCategory", t =>
                        {
                            t.HasComment("Tabla de asociación muchos-a-muchos entre productos internos y categorías. Permite que un producto pertenezca a múltiples categorías y que una categoría agrupe múltiples productos. No se permite la misma combinación producto-categoría dos veces.");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ProductProductSKU", b =>
                {
                    b.Property<int>("IdProductProductSKU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProductProductSKU")
                        .HasComment("Identificador único autoincremental de la asociación producto-SKU.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductProductSKU"));

                    b.Property<int>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("idProduct")
                        .HasComment("FK al producto interno.");

                    b.Property<int>("IdProductSKU")
                        .HasColumnType("int")
                        .HasColumnName("idProductSKU")
                        .HasComment("FK al SKU de código de barras.");

                    b.HasKey("IdProductProductSKU");

                    b.HasIndex("IdProductSKU");

                    b.HasIndex("IdProduct", "IdProductSKU")
                        .IsUnique()
                        .HasDatabaseName("UQ_productProductSKU_idProduct_idProductSKU");

                    b.ToTable("productProductSKU", t =>
                        {
                            t.HasComment("Tabla de asociación muchos-a-muchos entre productos internos y SKUs de código de barras. Permite que un producto interno (product) esté vinculado a múltiples SKUs escaneables y que un mismo SKU pueda usarse en varios productos.");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ProductSKU", b =>
                {
                    b.Property<int>("IdProductSKU")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idProductSKU")
                        .HasComment("Identificador único autoincremental del SKU.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductSKU"));

                    b.Property<string>("BrandProductSKU")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("brandProductSKU")
                        .HasComment("Marca o fabricante del producto. Ej: 'Nestlé', 'Unilever'.");

                    b.Property<string>("CodeProductSKU")
                        .IsRequired()
                        .HasMaxLength(48)
                        .IsUnicode(false)
                        .HasColumnType("varchar(48)")
                        .HasColumnName("codeProductSKU")
                        .HasComment("Código de barras del producto. Soporta EAN-8 (8 dígitos), EAN-13 (13 dígitos), UPC-A (12 dígitos) y otros formatos de hasta 48 caracteres.");

                    b.Property<string>("DescriptionProductSKU")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descriptionProductSKU")
                        .HasComment("Descripción detallada del producto: ingredientes, características, uso recomendado.");

                    b.Property<string>("NameProductSKU")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nameProductSKU")
                        .HasComment("Nombre completo del producto tal como aparece en el empaque.");

                    b.Property<string>("NetContent")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("netContent")
                        .HasComment("Contenido neto del producto con su unidad de medida. Ej: '500ml', '1kg', '12 unidades'.");

                    b.HasKey("IdProductSKU");

                    b.HasIndex("CodeProductSKU")
                        .IsUnique()
                        .HasDatabaseName("UQ_productSKU_codeProductSKU");

                    b.ToTable("productSKU", t =>
                        {
                            t.HasComment("Catálogo de SKUs de productos identificados por código de barras. Un SKU representa la unidad comercial exacta de un producto (marca + contenido + presentación). Múltiples productos internos pueden referenciar el mismo SKU a través de productProductSKU.");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRole")
                        .HasComment("Identificador único autoincremental del rol.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createAt")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Fecha y hora de creación del rol.");

                    b.Property<string>("DescriptionRole")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descriptionRole")
                        .HasComment("Descripción del nivel de acceso y permisos que otorga el rol.");

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nameRole")
                        .HasComment("Nombre único del rol. Valores del sistema: Developer, Admin, User.");

                    b.HasKey("IdRole");

                    b.HasIndex("NameRole")
                        .IsUnique()
                        .HasDatabaseName("UQ_role_nameRole");

                    b.ToTable("role", t =>
                        {
                            t.HasComment("Roles de acceso del sistema. Define los niveles de autorización: Developer (acceso total), Admin (acceso amplio), User (acceso básico). Los roles se asignan a usuarios a través de la tabla userRole.");
                        });

                    b.HasData(
                        new
                        {
                            IdRole = 1,
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionRole = "Acceso total al sistema",
                            NameRole = "Developer"
                        },
                        new
                        {
                            IdRole = 2,
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionRole = "Administrador con acceso amplio",
                            NameRole = "Admin"
                        },
                        new
                        {
                            IdRole = 3,
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionRole = "Usuario estándar",
                            NameRole = "User"
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUser")
                        .HasComment("Identificador único autoincremental del usuario.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("CodeUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codeUser")
                        .HasComment("Código único de identificación del usuario. Usado como nombre de usuario en el login.");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createAt")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Fecha y hora de creación del registro. Se asigna automáticamente a la fecha actual del servidor.");

                    b.Property<string>("EmailUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("emailUser")
                        .HasComment("Correo electrónico del usuario. Usado para notificaciones y envío de PIN.");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nameUser")
                        .HasComment("Nombre completo del usuario.");

                    b.Property<string>("PhoneUser")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phoneUser")
                        .HasComment("Número de teléfono del usuario (opcional). Formato libre, ej: '50683681485'.");

                    b.HasKey("IdUser");

                    b.HasIndex("CodeUser")
                        .IsUnique()
                        .HasDatabaseName("UQ_user_codeUser");

                    b.ToTable("user", t =>
                        {
                            t.HasComment("Usuarios del sistema que pueden autenticarse con JWT. Cada usuario puede tener uno o más roles (Developer, Admin, User).");
                        });

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            CodeUser = "S",
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailUser = "ezekiell1988@hotmail.com",
                            NameUser = "Ezequiel Baltodano Cubillo",
                            PhoneUser = "50683681485"
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.UserPin", b =>
                {
                    b.Property<int>("IdUserPin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUserPin")
                        .HasComment("Identificador único autoincremental del registro de PIN.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserPin"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createAt")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Fecha y hora en que se generó el PIN. Se usa para validar su vigencia.");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser")
                        .HasComment("FK al usuario propietario del PIN.");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("pin")
                        .HasComment("PIN numérico de 5 dígitos generado aleatoriamente y enviado al usuario por correo.");

                    b.HasKey("IdUserPin");

                    b.HasIndex("IdUser", "Pin")
                        .IsUnique()
                        .HasDatabaseName("UQ_userPin_idUser_pin");

                    b.ToTable("userPin", t =>
                        {
                            t.HasComment("PINs temporales de 5 dígitos usados para autenticación de dos factores. Se generan por solicitud y se envían al correo del usuario. Un PIN no puede repetirse para el mismo usuario hasta que expire o sea usado.");
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("IdUserRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUserRole")
                        .HasComment("Identificador único autoincremental de la asignación usuario-rol.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserRole"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createAt")
                        .HasDefaultValueSql("GETDATE()")
                        .HasComment("Fecha y hora en que se asignó el rol al usuario.");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("idRole")
                        .HasComment("FK al rol que se le asigna al usuario.");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser")
                        .HasComment("FK al usuario al que se le asigna el rol.");

                    b.HasKey("IdUserRole");

                    b.HasIndex("IdRole");

                    b.HasIndex("IdUser", "IdRole")
                        .IsUnique()
                        .HasDatabaseName("UQ_userRole_idUser_idRole");

                    b.ToTable("userRole", t =>
                        {
                            t.HasComment("Tabla de asociación muchos-a-muchos entre usuarios y roles. Un usuario puede tener múltiples roles y un rol puede asignarse a múltiples usuarios. No se permite asignar el mismo rol dos veces al mismo usuario.");
                        });

                    b.HasData(
                        new
                        {
                            IdUserRole = 1,
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRole = 1,
                            IdUser = 1
                        },
                        new
                        {
                            IdUserRole = 2,
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRole = 2,
                            IdUser = 1
                        },
                        new
                        {
                            IdUserRole = 3,
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRole = 3,
                            IdUser = 1
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Account", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Account", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("IdAccountParent")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.AccountingEntry", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Currency", "IdCurrencyNavigation")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("IdCurrency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyAccountApi.Domain.Entities.FiscalPeriod", "IdFiscalPeriodNavigation")
                        .WithMany("AccountingEntries")
                        .HasForeignKey("IdFiscalPeriod")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCurrencyNavigation");

                    b.Navigation("IdFiscalPeriodNavigation");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.AccountingEntryLine", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Account", "IdAccountNavigation")
                        .WithMany("AccountingEntryLines")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyAccountApi.Domain.Entities.AccountingEntry", "IdAccountingEntryNavigation")
                        .WithMany("AccountingEntryLines")
                        .HasForeignKey("IdAccountingEntry")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAccountApi.Domain.Entities.CostCenter", "IdCostCenterNavigation")
                        .WithMany("AccountingEntryLines")
                        .HasForeignKey("IdCostCenter")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("IdAccountNavigation");

                    b.Navigation("IdAccountingEntryNavigation");

                    b.Navigation("IdCostCenterNavigation");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.BankAccount", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Account", "IdAccountNavigation")
                        .WithMany("BankAccounts")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyAccountApi.Domain.Entities.Currency", "IdCurrencyNavigation")
                        .WithMany("BankAccounts")
                        .HasForeignKey("IdCurrency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdAccountNavigation");

                    b.Navigation("IdCurrencyNavigation");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Budget", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Account", "IdAccountNavigation")
                        .WithMany("Budgets")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyAccountApi.Domain.Entities.FiscalPeriod", "IdFiscalPeriodNavigation")
                        .WithMany("Budgets")
                        .HasForeignKey("IdFiscalPeriod")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdAccountNavigation");

                    b.Navigation("IdFiscalPeriodNavigation");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ContactContactType", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Contact", "Contact")
                        .WithMany("ContactContactTypes")
                        .HasForeignKey("IdContact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAccountApi.Domain.Entities.ContactType", "ContactType")
                        .WithMany("ContactContactTypes")
                        .HasForeignKey("IdContactType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("ContactType");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ExchangeRate", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Currency", "IdCurrencyNavigation")
                        .WithMany("ExchangeRates")
                        .HasForeignKey("IdCurrency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdCurrencyNavigation");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ProductProductCategory", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Product", "Product")
                        .WithMany("ProductProductCategories")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAccountApi.Domain.Entities.ProductCategory", "ProductCategory")
                        .WithMany("ProductProductCategories")
                        .HasForeignKey("IdProductCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ProductProductSKU", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Product", "Product")
                        .WithMany("ProductProductSKUs")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAccountApi.Domain.Entities.ProductSKU", "ProductSKU")
                        .WithMany("ProductProductSKUs")
                        .HasForeignKey("IdProductSKU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductSKU");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.UserPin", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.User", "User")
                        .WithMany("UserPins")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAccountApi.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Account", b =>
                {
                    b.Navigation("AccountingEntryLines");

                    b.Navigation("BankAccounts");

                    b.Navigation("Budgets");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.AccountingEntry", b =>
                {
                    b.Navigation("AccountingEntryLines");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Contact", b =>
                {
                    b.Navigation("ContactContactTypes");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ContactType", b =>
                {
                    b.Navigation("ContactContactTypes");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.CostCenter", b =>
                {
                    b.Navigation("AccountingEntryLines");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Currency", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("BankAccounts");

                    b.Navigation("ExchangeRates");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.FiscalPeriod", b =>
                {
                    b.Navigation("AccountingEntries");

                    b.Navigation("Budgets");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductProductCategories");

                    b.Navigation("ProductProductSKUs");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("ProductProductCategories");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ProductSKU", b =>
                {
                    b.Navigation("ProductProductSKUs");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.User", b =>
                {
                    b.Navigation("UserPins");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
