// <auto-generated />
using System;
using FamilyAccountApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyAccountApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320000702_AddContacts")]
    partial class AddContacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("IdContact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idContact");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContact"));

                    b.Property<string>("CodeContact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codeContact");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("IdContact");

                    b.HasIndex("CodeContact")
                        .IsUnique()
                        .HasDatabaseName("UQ_contact_codeContact");

                    b.ToTable("contact");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ContactContactType", b =>
                {
                    b.Property<int>("IdContactContactType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idContactContactType");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContactContactType"));

                    b.Property<int>("IdContact")
                        .HasColumnType("int")
                        .HasColumnName("idContact");

                    b.Property<int>("IdContactType")
                        .HasColumnType("int")
                        .HasColumnName("idContactType");

                    b.HasKey("IdContactContactType");

                    b.HasIndex("IdContactType");

                    b.HasIndex("IdContact", "IdContactType")
                        .IsUnique()
                        .HasDatabaseName("UQ_contactContactType_idContact_idContactType");

                    b.ToTable("contactContactType");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ContactType", b =>
                {
                    b.Property<int>("IdContactType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idContactType");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContactType"));

                    b.Property<string>("CodeContactType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codeContactType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("IdContactType");

                    b.HasIndex("CodeContactType")
                        .IsUnique()
                        .HasDatabaseName("UQ_contactType_codeContactType");

                    b.ToTable("contactType");

                    b.HasData(
                        new
                        {
                            IdContactType = 1,
                            CodeContactType = "CLI",
                            Name = "Cliente"
                        },
                        new
                        {
                            IdContactType = 2,
                            CodeContactType = "PRO",
                            Name = "Proveedor"
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRole");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DescriptionRole")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descriptionRole");

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nameRole");

                    b.HasKey("IdRole");

                    b.HasIndex("NameRole")
                        .IsUnique()
                        .HasDatabaseName("UQ_role_nameRole");

                    b.ToTable("role");

                    b.HasData(
                        new
                        {
                            IdRole = 1,
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionRole = "Acceso total al sistema",
                            NameRole = "Developer"
                        },
                        new
                        {
                            IdRole = 2,
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionRole = "Administrador con acceso amplio",
                            NameRole = "Admin"
                        },
                        new
                        {
                            IdRole = 3,
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DescriptionRole = "Usuario estándar",
                            NameRole = "User"
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("CodeUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codeUser");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EmailUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("emailUser");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nameUser");

                    b.Property<string>("PhoneUser")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phoneUser");

                    b.HasKey("IdUser");

                    b.HasIndex("CodeUser")
                        .IsUnique()
                        .HasDatabaseName("UQ_user_codeUser");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            CodeUser = "S",
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailUser = "ezekiell1988@hotmail.com",
                            NameUser = "Ezequiel Baltodano Cubillo",
                            PhoneUser = "50683681485"
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.UserPin", b =>
                {
                    b.Property<int>("IdUserPin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUserPin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserPin"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("pin");

                    b.HasKey("IdUserPin");

                    b.HasIndex("IdUser", "Pin")
                        .IsUnique()
                        .HasDatabaseName("UQ_userPin_idUser_pin");

                    b.ToTable("userPin");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("IdUserRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUserRole");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserRole"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("idRole");

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.HasKey("IdUserRole");

                    b.HasIndex("IdRole");

                    b.HasIndex("IdUser", "IdRole")
                        .IsUnique()
                        .HasDatabaseName("UQ_userRole_idUser_idRole");

                    b.ToTable("userRole");

                    b.HasData(
                        new
                        {
                            IdUserRole = 1,
                            CreateAt = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdRole = 1,
                            IdUser = 1
                        });
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ContactContactType", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Contact", "Contact")
                        .WithMany("ContactContactTypes")
                        .HasForeignKey("IdContact")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAccountApi.Domain.Entities.ContactType", "ContactType")
                        .WithMany("ContactContactTypes")
                        .HasForeignKey("IdContactType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("ContactType");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.UserPin", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.User", "User")
                        .WithMany("UserPins")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAccountApi.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Contact", b =>
                {
                    b.Navigation("ContactContactTypes");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.ContactType", b =>
                {
                    b.Navigation("ContactContactTypes");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.User", b =>
                {
                    b.Navigation("UserPins");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
