// <auto-generated />
using FamilyAccountApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyAccountApi.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319174725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<string>("CodeUser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codeUser");

                    b.Property<string>("EmailUser")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("emailUser");

                    b.Property<string>("NameUser")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nameUser");

                    b.Property<string>("PhoneUser")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phoneUser");

                    b.HasKey("IdUser");

                    b.HasIndex("CodeUser")
                        .IsUnique()
                        .HasDatabaseName("UQ_user_codeUser");

                    b.ToTable("user");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.UserPin", b =>
                {
                    b.Property<int>("IdUserPin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idUserPin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUserPin"));

                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("idUser");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("pin");

                    b.HasKey("IdUserPin");

                    b.HasIndex("IdUser", "Pin")
                        .IsUnique()
                        .HasDatabaseName("UQ_userPin_idUser_pin");

                    b.ToTable("userPin");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.UserPin", b =>
                {
                    b.HasOne("FamilyAccountApi.Domain.Entities.User", "User")
                        .WithMany("UserPins")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyAccountApi.Domain.Entities.User", b =>
                {
                    b.Navigation("UserPins");
                });
#pragma warning restore 612, 618
        }
    }
}
